package com.fileprocessor;

import java.io.*;
import java.nio.file.*;
import java.util.Random;

/**
 * Generates realistic sample .txt files for demonstration purposes.
 * Simulates log files, data files, and report files.
 */
public class SampleFileGenerator {

    private static final String[] LOREM_WORDS = {
        "thread", "synchronization", "concurrent", "executor", "runnable",
        "callable", "future", "latch", "semaphore", "monitor", "lock",
        "atomic", "volatile", "deadlock", "race", "condition", "pool",
        "blocking", "queue", "priority", "scheduled", "fork", "join",
        "parallel", "stream", "pipeline", "performance", "throughput",
        "latency", "scalable", "distributed", "cache", "memory", "heap"
    };

    private static final Random RANDOM = new Random(42L);

    public static void generate(Path dir) throws IOException {
        Files.createDirectories(dir);

        // Generate 8 diverse sample files
        generateLogFile(dir.resolve("server_access.log.txt"),      500);
        generateLogFile(dir.resolve("application_errors.log.txt"), 300);
        generateDataFile(dir.resolve("employee_records.txt"),      200);
        generateDataFile(dir.resolve("product_catalog.txt"),       350);
        generateReportFile(dir.resolve("q1_sales_report.txt"),     150);
        generateReportFile(dir.resolve("q2_sales_report.txt"),     180);
        generateCodeFile(dir.resolve("config_properties.txt"),     100);
        generateProseFile(dir.resolve("project_documentation.txt"),120);

        System.out.println("Sample files generated in: " + dir.toAbsolutePath());
    }

    private static void generateLogFile(Path path, int lines) throws IOException {
        String[] levels   = {"INFO", "WARN", "ERROR", "DEBUG"};
        String[] endpoints = {"/api/users", "/api/products", "/api/orders", "/health", "/metrics"};
        String[] methods   = {"GET", "POST", "PUT", "DELETE"};

        try (PrintWriter w = new PrintWriter(Files.newBufferedWriter(path))) {
            for (int i = 0; i < lines; i++) {
                String level    = levels[RANDOM.nextInt(levels.length)];
                String endpoint = endpoints[RANDOM.nextInt(endpoints.length)];
                String method   = methods[RANDOM.nextInt(methods.length)];
                int    status   = RANDOM.nextBoolean() ? 200 : (RANDOM.nextBoolean() ? 404 : 500);
                int    ms       = 10 + RANDOM.nextInt(990);
                w.printf("2024-%02d-%02d %02d:%02d:%02d [%s] %s %s HTTP/1.1 %d %dms%n",
                        1 + RANDOM.nextInt(12), 1 + RANDOM.nextInt(28),
                        RANDOM.nextInt(24), RANDOM.nextInt(60), RANDOM.nextInt(60),
                        level, method, endpoint, status, ms);
            }
        }
    }

    private static void generateDataFile(Path path, int lines) throws IOException {
        try (PrintWriter w = new PrintWriter(Files.newBufferedWriter(path))) {
            w.println("ID,Name,Department,Salary,JoinDate");
            for (int i = 1; i <= lines; i++) {
                String name   = randomWord() + " " + randomWord();
                String dept   = new String[]{"Engineering","Marketing","Finance","HR","Ops"}[RANDOM.nextInt(5)];
                int    salary = 40000 + RANDOM.nextInt(120000);
                w.printf("%04d,%s,%s,%d,2020-%02d-%02d%n",
                        i, name, dept, salary,
                        1 + RANDOM.nextInt(12), 1 + RANDOM.nextInt(28));
            }
        }
    }

    private static void generateReportFile(Path path, int lines) throws IOException {
        try (PrintWriter w = new PrintWriter(Files.newBufferedWriter(path))) {
            w.println("=".repeat(60));
            w.println("QUARTERLY SALES PERFORMANCE REPORT");
            w.println("Generated by Multithreaded Report Engine");
            w.println("=".repeat(60));
            w.println();
            for (int i = 0; i < lines; i++) {
                String region  = new String[]{"North","South","East","West","Central"}[RANDOM.nextInt(5)];
                String product = randomWord() + " Pro " + (1 + RANDOM.nextInt(5));
                int    units   = 10 + RANDOM.nextInt(990);
                double revenue = units * (9.99 + RANDOM.nextInt(990));
                w.printf("Region: %-8s | Product: %-20s | Units: %4d | Revenue: $%,.2f%n",
                        region, product, units, revenue);
            }
        }
    }

    private static void generateCodeFile(Path path, int lines) throws IOException {
        try (PrintWriter w = new PrintWriter(Files.newBufferedWriter(path))) {
            for (int i = 0; i < lines; i++) {
                String key   = randomWord() + "." + randomWord() + ".config";
                String value = randomWord() + "_" + (RANDOM.nextInt(9999));
                w.printf("%s=%s%n", key, value);
            }
        }
    }

    private static void generateProseFile(Path path, int paragraphs) throws IOException {
        try (PrintWriter w = new PrintWriter(Files.newBufferedWriter(path))) {
            w.println("PROJECT DOCUMENTATION — Multithreaded File Processor");
            w.println("Author: Java Developer Intern | Task 3");
            w.println();
            for (int p = 0; p < paragraphs; p++) {
                StringBuilder sb = new StringBuilder();
                int wordCount = 20 + RANDOM.nextInt(40);
                for (int i = 0; i < wordCount; i++) {
                    if (i > 0) sb.append(' ');
                    sb.append(randomWord());
                }
                sb.append('.');
                w.println(sb);
                w.println();
            }
        }
    }

    private static String randomWord() {
        return LOREM_WORDS[RANDOM.nextInt(LOREM_WORDS.length)];
    }
}
